
name: Scrape data every Friday

on:
  workflow_dispatch:
  schedule:
    - cron: "00 19 * * 5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |-
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
        heroku plugins:install heroku-builds

    - name: Scrape data from Energy Regulatory Office
      run: |-
        scrapy crawl holder
        scrapy crawl heatgen
        scrapy crawl electricitygen

    - name: Push database to Heroku
      run: |-
        datasette publish heroku licenses.db -n licenses-ero
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
